# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Create Release

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew -Pnet.minecraftforge.gradle.disableUpdateChecker=true build
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          Changes in this Release
          - Add JEI two-way search mode (embeddedt)
          - Add ability to copy redstone mode for wrench
          - Fixed dupe glitch involving two external storages connected to the same block
          - Fixed item in autocrafting settings gui being extractable
          - Fixed JEI recipe transfer kicking the player sometimes
          - Fixed grid not showing any items in some very rare edge cases
          - Disabled automatic crafter unlocking (breaks crafting tasks in unwanted situations)
          - Restore compatibility with QuantumStorage and other mods
        draft: false
        prerelease: false
    - name: Upload jars to release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./build/libs/*
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true
