# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Create Release

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Setup forge
      run: ./gradlew setupCiWorkspace
    - name: Build with Gradle
      run: ./gradlew build
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          Changes in this Release
          - Added creative range upgrade
          - Added scrolling support to pattern grid (scroll to change amount of items)
          - Removed Gregtech pattern rendering blacklist
          - Fixed completion percentage of crafting tasks rounding in the wrong direction
          - Fixed filtering in disk manipulator not working correctly
          - Fixed various thing being able to run without power
          - Fixed some controller gui issues
          - Fixed big amount of patterns freezing the client when rendering
        draft: false
        prerelease: false
    - name: Upload jars to release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./build/libs/*
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true
